[package]
name = "rust-async-spider"
version = "0.1.0"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
surf = "2.2.0"
scraper = "0.12.0"
colored = "2.0.0"
